[package]
name = "xtask"
version = "0.1.2"
edition = "2021"
description = "Build and test automation for IPS"
publish = false

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.6", features = ["derive"] }
