[package]
name = "ports"
description.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.59"
clap = {version = "4", features = [ "derive", "env" ] }
specfile = {path = "../specfile"}
shellexpand = "3"
url = { version = "2.2.2", features = ["serde"]}
reqwest = { version = "0.12", features = ["blocking"] }
which = "8"
libips = {path = "../libips"}
thiserror = "*"
